[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

[rpc_endpoints]
u2u_testnet = "https://rpc-nebulas-testnet.uniultra.xyz"
local = "http://127.0.0.1:8545"

[etherscan]
u2u_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.u2uscan.xyz/api" }

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"